# Generated by Django 2.1.3 on 2018-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_category',
            name='CREATED_DATE',
            field=models.DateTimeField(),
        ),
    ]
